apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-city-analytics.fullname" . | default "smart-city-analytics" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: smart-city-analytics
  template:
    metadata:
      labels:
        app: smart-city-analytics
    spec:
      containers:
      - name: api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
